on:
  push:
    branches:
      - main
name: upload-coverage-report
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: test and generate coverage report
        run: make test.cover
      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
